export const countryNameToCode: Record<string, string> = {
    'Russia': 'RU',
    'Rossiya': 'RU',
    'Russian Federation': 'RU',
    'United States': 'US',
    'USA': 'US',
    'Ukraine': 'UA',
    'Belarus': 'BY',
    'Kazakhstan': 'KZ',
    'Uzbekistan': 'UZ',
    'Kyrgyzstan': 'KG',
    'Tajikistan': 'TJ',
    'Turkmenistan': 'TM',
    'Azerbaijan': 'AZ',
    'Armenia': 'AM',
    'Georgia': 'GE',
    'Turkey': 'TR',
    'United Arab Emirates': 'AE',
    'UAE': 'AE',
    'Germany': 'DE',
    'France': 'FR',
    'Italy': 'IT',
    'Spain': 'ES',
    'United Kingdom': 'GB',
    'UK': 'GB',
    'Great Britain': 'GB',
    'Israel': 'IL',
    'Canada': 'CA',
    'China': 'CN',
    'Japan': 'JP',
    'South Korea': 'KR',
    'India': 'IN',
    'Brazil': 'BR',
    'Argentina': 'AR',
    'Mexico': 'MX',
    'Australia': 'AU',
    'New Zealand': 'NZ',
    'Netherlands': 'NL',
    'Belgium': 'BE',
    'Switzerland': 'CH',
    'Sweden': 'SE',
    'Norway': 'NO',
    'Finland': 'FI',
    'Denmark': 'DK',
    'Poland': 'PL',
    'Czech Republic': 'CZ',
    'Austria': 'AT',
    'Hungary': 'HU',
    'Greece': 'GR',
    'Portugal': 'PT',
    'Ireland': 'IE',
    'Romania': 'RO',
    'Bulgaria': 'BG',
    'Serbia': 'RS',
    'Croatia': 'HR',
    'Slovakia': 'SK',
    'Slovenia': 'SI',
    'Estonia': 'EE',
    'Latvia': 'LV',
    'Lithuania': 'LT',
    'Moldova': 'MD',
    'Cyprus': 'CY',
    'Malta': 'MT',
    'Iceland': 'IS',
    'Saudi Arabia': 'SA',
    'Qatar': 'QA',
    'Kuwait': 'KW',
    'Bahrain': 'BH',
    'Oman': 'OM',
    'Egypt': 'EG',
    'Thailand': 'TH',
    'Vietnam': 'VN',
    'Indonesia': 'ID',
    'Malaysia': 'MY',
    'Singapore': 'SG',
    'Philippines': 'PH'
};

export const getCountryCode = (countryName: string): string | undefined => {
    if (!countryName) return undefined;

    // Direct lookup
    if (countryNameToCode[countryName]) return countryNameToCode[countryName];

    // Case insensitive
    const upper = countryName.toUpperCase();
    const entry = Object.entries(countryNameToCode).find(([k]) => k.toUpperCase() === upper);
    return entry ? entry[1] : undefined;
};
