#!/usr/bin/env python3
"""
Comprehensive service translation fix:
1. Ensure all services have both name_ru and name_en
2. Remove any bad prefixes from descriptions
3. Set proper Russian descriptions
4. Clear bad translations to force re-translation
"""

import sys
from pathlib import Path

backend_dir = Path(__file__).parent.parent.parent
sys.path.insert(0, str(backend_dir))

from db.connection import get_db_connection

# Mapping of English names to Russian
TRANSLATIONS = {
    # Nails
    'acrylic extension': 'Наращивание акрилом',
    'acrylic overlay': 'Покрытие акрилом',
    'change gel': 'Смена гель-лака',
    'french': 'Французский маникюр',
    'gel extension': 'Наращивание гелем',
    'gel overlay': 'Покрытие гелем',
    'hard gel': 'Твердый гель',
    'nail design': 'Дизайн ногтей',
    'pedicure basic': 'Базовый педикюр',
    'pedicure classic': 'Классический педикюр',
    'pedicure gel': 'Педикюр с гель-лаком',
    'podology': 'Подология',
    'remove classic': 'Снятие обычного лака',
    'remove gel': 'Снятие гель-лака',
    'remove nail extensions': 'Снятие наращенных ногтей',
    'spa pedicure': 'СПА-педикюр',
    
    # Hair
    'hair cut': 'Стрижка',
    'hair wash': 'Мытье волос',
    'hair style': 'Укладка',
    'hair treatment': 'Уход за волосами',
    'hair extension (only removal)': 'Снятие наращенных волос',
    'hair extensions (1 can)': 'Наращивание волос (1 капсула)',
    'trimming without wash': 'Подравнивание без мытья',
    
    # Massage
    'anti-cellulite massage': 'Антицеллюлитный массаж',
    'back 30 min': 'Массаж спины 30 мин',
    'back massage (5-10)': 'Массаж спины (курс)',
    'classic general massage': 'Классический массаж',
    'full body 60 min': 'Массаж всего тела',
    'head 40 min': 'Массаж головы',
    'hotstone': 'Стоун-массаж',
    'leg/feet/ hand 40 min': 'Массаж ног/рук',
    'moroccan bath loofa': 'Марокканская баня с люфой',
    'moroccan bathhouse': 'Марокканская баня',
    'neck & shoulder 30 min': 'Массаж шеи и плеч',
    'sculpture body massage': 'Скульптурный массаж',
    
    # Promo
    'blow dry packages 5': 'Пакет укладок (5 шт)',
    'combo basic 150': 'Комбо базовый',
    'promo 390': 'Акция 390',
    'promo mani pedi 250': 'Акция маникюр+педикюр',
    'promotion overlay manicure': 'Акционный маникюр',
    
    # Waxing
    'brazilian': 'Бразильская эпиляция',
    'cheeks': 'Эпиляция щек',
    'full body': 'Эпиляция всего тела',
    'under arms': 'Эпиляция подмышек',
    'upper lip': 'Эпиляция верхней губы',
}

def fix_all_services():
    """Comprehensive fix for all services"""
    
    print("🔧 Comprehensive service translation fix...")
    
    conn = get_db_connection()
    cursor = conn.cursor()
    
    try:
        # 1. Get all services
        cursor.execute("SELECT id, name, name_ru, name_en FROM services")
        services = cursor.fetchall()
        
        print(f"\n📋 Processing {len(services)} services...")
        
        fixed_count = 0
        
        for service_id, name, name_ru, name_en in services:
            updates = {}
            
            # Determine the best Russian and English names
            current_ru = name_ru or name
            current_en = name_en or name
            
            # Check if we have a translation for this service
            if current_en:
                en_lower = current_en.lower().strip()
                if en_lower in TRANSLATIONS:
                    updates['name_ru'] = TRANSLATIONS[en_lower]
                    updates['name_en'] = current_en
                elif not current_ru or current_ru == current_en:
                    # No Russian name, keep as-is for now
                    updates['name_ru'] = current_en
                    updates['name_en'] = current_en
            
            # Update if we have changes
            if updates:
                set_clause = ', '.join([f"{k} = %s" for k in updates.keys()])
                values = list(updates.values()) + [service_id]
                cursor.execute(f"UPDATE services SET {set_clause} WHERE id = %s", values)
                
                print(f"   ✅ ID {service_id}: {current_en} → {updates.get('name_ru', current_ru)}")
                fixed_count += 1
        
        # 2. Clear all bad descriptions (will be regenerated by translation system)
        print("\n🧹 Clearing bad descriptions...")
        cursor.execute("""
            UPDATE services
            SET description = NULL,
                description_en = NULL,
                description_ar = NULL,
                description_de = NULL,
                description_es = NULL,
                description_fr = NULL,
                description_hi = NULL,
                description_kk = NULL,
                description_pt = NULL
            WHERE description LIKE '%Услуга:%' 
               OR description LIKE '%Service:%'
               OR description LIKE '%Служба:%'
               OR description LIKE '%Сервис:%'
        """)
        
        print("   ✅ Cleared bad descriptions")
        
        conn.commit()
        print(f"\n✅ Fixed {fixed_count} services!")
        print("\n💡 Next: Run 'npm run db:i18n:auto' to regenerate all translations")
        
    except Exception as e:
        conn.rollback()
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        raise
    finally:
        cursor.close()
        conn.close()

if __name__ == "__main__":
    fix_all_services()
